
logging:
  level:
    org:
      hibernate:
        - SQL: DEBUG
        - type: TRACE
spring:
  datasource:
    url: jdbc:mysql://skrao-app-server:3306/t_cmgr_db?useSSL=false&useLegacyDatetimeCode=false
    username: web_user
    password: XXXXXXX
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

credmgr:
  api:
    ping-message: Hi there, server is up!
    admin-ping-message: Hi Admin, Server is up