logging:
  level:
    org.hibernate.SQL: INFO

spring:
  datasource:
    url: jdbc:mysql://${db_host}:3306/p_cmgr_db?useSSL=false&useLegacyDatetimeCode=false
    username: ${db_user}
    password: ${db_password}

server:
  servlet:
    context-path: /v1/credmgr-api

credmgr:
  api:
    token-duration: 30
    whitelisted-host: ${white_listed_host}