logging:
  level:
    org.hibernate.SQL: TRACE
spring:
  datasource:
    url: jdbc:mysql://${db_host}:3306/t_cmgr_db?useSSL=false&useLegacyDatetimeCode=false
    username: ${db_user}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
server:
  servlet:
    context-path: /v1/credmgr-api
credmgr:
  api:
    token-duration: 30
    whitelisted-host: ${white_listed_host}
