logging:
  level:
    org.hibernate.SQL: INFO

spring:
  datasource:
    url: jdbc:mysql://skrao-app-server:3306/p_cmgr_db?useSSL=false&useLegacyDatetimeCode=false
    username: ${db_user}
    password: ${db_password}