
logging:
  level:
    org.hibernate.SQL: ERROR

spring:
  datasource:
    url: jdbc:mysql://skrao-app-server:3306/t_cmgr_db?useSSL=false&useLegacyDatetimeCode=false
    username: ${db_user}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: /v1/credmgr-api

credmgr:
  api:
    ping-message: Hi there, server is up!
    admin-ping-message: Hi Admin, Server is up